In [8]:
import numpy as np

# 定义向量 a 和 b
a = np.array([1, -1]).reshape(-1,1)
b = np.array([1, 1]).reshape(-1,1)

# 计算向量 a 的范数
a_norm = np.linalg.norm(a)

# 计算投影向量 p
p = (np.dot(a, b) / (a_norm ** 2)) * a

print("投影向量 p:", p)


ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [10]:
import numpy as np

# 定义列向量 a 和 b
a = np.array([[1], [-1]])
b = np.array([[1], [1]])

# 计算向量 a 的范数（模）
a_norm = np.linalg.norm(a)

# 计算向量 a 和 b 的点积
dot_product = np.dot(a.T, b)[0, 0]

# 计算投影向量 p
projection = (dot_product / (a_norm ** 2)) * a

print("向量 a 的范数:", a_norm)
print("向量 a 和 b 的点积:", dot_product)
print("向量 b 在向量 a 上的投影:", projection)


向量 a 的范数: 1.4142135623730951
向量 a 和 b 的点积: 0
向量 b 在向量 a 上的投影: [[ 0.]
 [-0.]]


In [28]:
# 定义列向量 A
A = np.array([[-1],
              [2],
              [2]])

# 计算 A 的转置
AT = A.T

# 计算 AAT
AAT = np.dot(A, AT)

# 计算 A 的转置的 Frobenius 范数
AT_norm = np.linalg.norm(AT)

# 计算投影矩阵 P
P1_fraction = np.vectorize(Fraction)(AAT) / (Fraction(AT_norm) ** 2)

print("矩阵 A 的转置:\n", AT)
print("矩阵 AAT:\n", AAT)
print("矩阵 A 的转置的 Frobenius 范数:", AT_norm)
print("投影矩阵 P:\n", P1_fraction)

矩阵 A 的转置:
 [[-1  2  2]]
矩阵 AAT:
 [[ 1 -2 -2]
 [-2  4  4]
 [-2  4  4]]
矩阵 A 的转置的 Frobenius 范数: 3.0
投影矩阵 P:
 [[Fraction(1, 9) Fraction(-2, 9) Fraction(-2, 9)]
 [Fraction(-2, 9) Fraction(4, 9) Fraction(4, 9)]
 [Fraction(-2, 9) Fraction(4, 9) Fraction(4, 9)]]


In [29]:
'''
# 定义列向量 A
E = np.array([[2],
              [2],
              [-1]])

# 计算 A 的转置
ET = E.T

# 计算 AAT
EET = np.dot(E, ET)

# 计算 A 的转置的 Frobenius 范数
ET_norm = np.linalg.norm(ET)

# 计算投影矩阵 P
P2 = EET / (ET_norm ** 2)

print("矩阵 A 的转置:\n", ET)
print("矩阵 AAT:\n", EET)
print("矩阵 A 的转置的 Frobenius 范数:", ET_norm)
print("投影矩阵 P:\n", P2)
'''

import numpy as np
from fractions import Fraction

# 定义列向量 E
E = np.array([[2],
              [2],
              [-1]])

# 计算 E 的转置
ET = E.T

# 计算 EET
EET = np.dot(E, ET)

# 计算 E 的转置的 Frobenius 范数
ET_norm = np.linalg.norm(ET)

# 计算投影矩阵 P2，使用 fractions.Fraction 对象
P2_fraction = np.vectorize(Fraction)(EET) / (Fraction(ET_norm) ** 2)

print("矩阵 E 的转置:\n", ET)
print("矩阵 EET:\n", EET)
print("矩阵 E 的转置的 Frobenius 范数:", ET_norm)
print("投影矩阵 P2（分数形式）:\n", P2_fraction)



矩阵 E 的转置:
 [[ 2  2 -1]]
矩阵 EET:
 [[ 4  4 -2]
 [ 4  4 -2]
 [-2 -2  1]]
矩阵 E 的转置的 Frobenius 范数: 3.0
投影矩阵 P2（分数形式）:
 [[Fraction(4, 9) Fraction(4, 9) Fraction(-2, 9)]
 [Fraction(4, 9) Fraction(4, 9) Fraction(-2, 9)]
 [Fraction(-2, 9) Fraction(-2, 9) Fraction(1, 9)]]


In [31]:
import numpy as np

# 方法1: 使用 numpy.dot 函数
result_dot = np.dot(P1_fraction, P2_fraction)

# 方法2: 使用 @ 运算符
result_at = P1_fraction @ P2_fraction

print("使用 numpy.dot 计算的点积结果:\n", result_dot)
print("\n使用 @ 运算符计算的点积结果:\n", result_at)


使用 numpy.dot 计算的点积结果:
 [[Fraction(0, 1) Fraction(0, 1) Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(0, 1)]]

使用 @ 运算符计算的点积结果:
 [[Fraction(0, 1) Fraction(0, 1) Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(0, 1)]]


In [32]:
import numpy as np
from fractions import Fraction

# 定义两个 3x3 矩阵 A 和 B
Z1 = np.array([[1, -2, -2],
              [-2, 4, 4],
              [-2, 4, 4]])

Z2 = np.array([[4, 4, -2],
              [4, 4, -2],
              [-2, -2, 1]])

result_at = Z1 @ Z2

result_at

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
# 定义列向量 A
G = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1],
              [0, 0, 0]])

# 计算 A 的转置
GT = G.T

# 计算 AAT
GGT = np.dot(G, GT)

# 计算 A 的转置的 Frobenius 范数
GT_norm = np.linalg.norm(GT)

# 计算投影矩阵 P
PG_fraction = np.vectorize(Fraction)(GGT) / (Fraction(GT_norm) ** 2)


print("矩阵 A 的转置:\n", GT)
print("矩阵 AAT:\n", GGT)
print("矩阵 A 的转置的 Frobenius 范数:", GT_norm)
print("投影矩阵 P:\n", PG_fraction)

矩阵 A 的转置:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
矩阵 AAT:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 0]]
矩阵 A 的转置的 Frobenius 范数: 1.7320508075688772
投影矩阵 P:
 [[Fraction(5070602400912917605986812821504, 15211807202738751055289669474361)
  Fraction(0, 1) Fraction(0, 1) Fraction(0, 1)]
 [Fraction(0, 1)
  Fraction(5070602400912917605986812821504, 15211807202738751055289669474361)
  Fraction(0, 1) Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1)
  Fraction(5070602400912917605986812821504, 15211807202738751055289669474361)
  Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(0, 1) Fraction(0, 1)]]


In [42]:
X1 = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0]])

X2 = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1],
              [0, 0, 0]])

resultX = X1 @ X2

resultX

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [44]:
# 计算逆矩阵

resultX_inv = np.linalg.inv(resultX)

resultX_inv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
resultP = X2 @ X1

resultP

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [7]:
import numpy as np

# 定义矩阵A
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 0]])

# 计算矩阵A的转置
A_T = A.T

# 计算投影矩阵P
P = A @ np.linalg.inv(A_T @ A) @ A_T

print("投影矩阵P:")
print(P)


投影矩阵P:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [8]:
# 定义列向量b
b = np.array([1, 2, 3, 4])

# 计算投影结果
result = P @ b

print("投影结果:")
print(result)

投影结果:
[1. 2. 3. 0.]
