In [2]:
import numpy as np

# 定义向量集合
v1 = np.array([1, -1, 0, 0]).reshape(-1, 1)
v2 = np.array([1, 0, -1, 0]).reshape(-1, 1)
v3 = np.array([1, 0, 0, -1]).reshape(-1, 1)
v4 = np.array([0, 1, -1, 0]).reshape(-1, 1)
v5 = np.array([0, 1, 0, -1]).reshape(-1, 1)
v6 = np.array([0, 0, 1, -1]).reshape(-1, 1)

# 构建矩阵
matrix = np.column_stack((v1, v2, v3, v4, v5, v6))

# 计算矩阵的秩
rank = np.linalg.matrix_rank(matrix)

print("矩阵的秩为:", rank)

矩阵的秩为: 3


In [3]:
# Confirm the REF
import sympy
from sympy import Matrix, Rational, sqrt, symbols
import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt

V = Matrix([
    [1, 1, 1, 0, 0, 0],
    [-1, 0, 0, 1, 1, 0],
    [0, -1, 0, -1, 0, 1],
    [0, 0, -1, 0, -1, -1]
])

ref_V = V.echelon_form()
ref_V

Matrix([
[1, 1, 1, 0, 0, 0],
[0, 1, 1, 1, 1, 0],
[0, 0, 1, 0, 1, 1],
[0, 0, 0, 0, 0, 0]])

In [11]:
u1 = Matrix([
    [1, 2, 3],
    [3, 1 ,2],
    [2, 3, 1],  
])

ref_u1 = u1.echelon_form()
ref_u1

Matrix([
[1,  2,  3],
[0, -5, -7],
[0,  0, 18]])

In [12]:
W = Matrix([
    [1, 2, -3],
    [-3, 1 ,2],
    [2, -3, 1],  
])

ref_W = W.echelon_form()
ref_W

Matrix([
[1, 2, -3],
[0, 7, -7],
[0, 0,  0]])

In [33]:
from itertools import combinations

# 定义矩阵 U
U = np.array([
    [2, 3, 4, 1],
    [0, 6, 7, 0],
    [0, 0, 0, 9],
    [0, 0, 0, 0],
])

# 获取矩阵 U 的列数
num_columns = U.shape[1]

# 生成所有可能的三列组合
all_combinations = list(combinations(range(num_columns), 3))

# 输出所有组合
for combo in all_combinations:
    selected_columns = U[:, combo]
    if np.linalg.matrix_rank(selected_columns) == len(combo):
        print(f"线性无关的三列组合：{combo}")
        print(selected_columns)
        print("\n")

线性无关的三列组合：(0, 1, 3)
[[2 3 1]
 [0 6 0]
 [0 0 9]
 [0 0 0]]


线性无关的三列组合：(0, 2, 3)
[[2 4 1]
 [0 7 0]
 [0 0 9]
 [0 0 0]]


线性无关的三列组合：(1, 2, 3)
[[3 4 1]
 [6 7 0]
 [0 0 9]
 [0 0 0]]




In [43]:
U = Matrix([
    [2, 3, 4, 1],
    [0, 6, 7, 0],
    [0, 0, 0, 9],
    [0, 0, 0, 0],
])

# 看看ref
rref_U, ii = U.rref()
rref_U

Matrix([
[1, 0, 1/4, 0],
[0, 1, 7/6, 0],
[0, 0,   0, 1],
[0, 0,   0, 0]])

In [44]:
ref_U = U.echelon_form()
ref_U

Matrix([
[2, 3, 4, 1],
[0, 6, 7, 0],
[0, 0, 0, 9],
[0, 0, 0, 0]])

In [23]:
from itertools import combinations

# 定义矩阵 
Z = np.array([
    [2, 3, 4, 1],
    [0, 6, 7, 0],
    [0, 0, 0, 9],
    [4, 6, 8, 2],
])

# 获取矩阵的列数
num_columns = Z.shape[1]

# 生成所有可能的三列组合
all_combinations = list(combinations(range(num_columns), 3))

# 输出所有组合
for combo in all_combinations:
    selected_columns = Z[:, combo]
    if np.linalg.matrix_rank(selected_columns) == len(combo):
        print(f"线性无关的三列组合：{combo}")
        print(selected_columns)
        print("\n")

线性无关的三列组合：(0, 1, 3)
[[2 3 1]
 [0 6 0]
 [0 0 9]
 [4 6 2]]


线性无关的三列组合：(0, 2, 3)
[[2 4 1]
 [0 7 0]
 [0 0 9]
 [4 8 2]]


线性无关的三列组合：(1, 2, 3)
[[3 4 1]
 [6 7 0]
 [0 0 9]
 [6 8 2]]




In [45]:
A = Matrix([
    [2, 3, 4, 1],
    [0, 6, 7, 0],
    [0, 0, 0, 9],
    [4, 6, 8, 2],
])

# 看看ref
rref_A, ii = A.rref()
rref_A

Matrix([
[1, 0, 1/4, 0],
[0, 1, 7/6, 0],
[0, 0,   0, 1],
[0, 0,   0, 0]])

In [46]:
ref_A = A.echelon_form()
ref_A

Matrix([
[2, 3, 4, 1],
[0, 6, 7, 0],
[0, 0, 0, 9],
[0, 0, 0, 0]])

In [5]:
T = Matrix([
    [2, 3, 1],
    [0, 6, 0],
    [0, 0, 9],
    [0, 0, 0]
])

ref_T = T.echelon_form()
ref_T

Matrix([
[2, 3, 1],
[0, 6, 0],
[0, 0, 9],
[0, 0, 0]])

In [90]:
# 定义向量集合
w1 = np.array([2, 0, 0, 4]).reshape(-1, 1)
w2 = np.array([3, 6, 0, 6]).reshape(-1, 1)
w3 = np.array([4, 7, 0, 8]).reshape(-1, 1)
w4 = np.array([0, 0, 9, 2]).reshape(-1, 1)

# 构建矩阵
matrix = np.column_stack((w1, w3, w4))

# 计算矩阵的秩
rank = np.linalg.matrix_rank(matrix)

print("矩阵的秩为:", rank)

矩阵的秩为: 3
